# -*- coding: utf-8 -*-
"""20221BCA0301(3).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BIwkGrh9g4j3b-tuyq1e0iNYY4y7TBrh

## ***The IterTools module***
The itertools module contains a number of commonly used iterators as well as functions for combining several iterators.

The module’s functions fall into a few broad classes:
•	Functions that create a new iterator based on an existing iterator.

•	Functions for treating an iterator’s elements as function arguments.

•	Functions for selecting portions of an iterator’s output.

•	A function for grouping an iterator’s output

# ***Creating New Iterators***

***1.count*** : itertools.count(start, step) returns an infinite stream of evenly spaced values. You can optionally supply the starting number, which defaults to 0, and the interval between numbers, which defaults to 1
"""

from itertools import count

for number in count(start=1, step=2):
	if number > 20:
		break
	print(number) # print statement

"""Different types of iterators provided by this module are:

# Infinite iterators

# Combinatoric iterators

# Terminating iterators

## ***Infinite Iterators***
Iterator in Python is any Python type that can be used with a ‘for in loop’. Python lists, tuples, dictionaries, and sets are all examples of inbuilt iterators.
But it is not necessary that an iterator object has to exhaust, sometimes it can be infinite. Such types of iterators are known as Infinite iterators

Python provides three types of infinite iterators:

1***. count(start, step):*** This iterator starts printing from the “start” number and prints infinitely. If steps are mentioned, the numbers are skipped else step is 1 by default. See the below example for its use with for in loop.
"""

# Python program to demonstrate
# infinite iterators

import itertools

# for in loop
for i in itertools.count(5, 5):
	if i == 45:
		break
	else:
		print(i, end=" ")

"""# ***2. cycle(iterable):*** This iterator prints all values in order from the passed container. It restarts printing from the beginning again when all elements are printed in a cyclic manner."""

# Python program to demonstrate
# infinite iterators

import itertools

count = 0

# for in loop
for i in itertools.cycle('ACB'):
	if count > 7:
		break
	else:
		print(i, end=" ")
		count += 1

#Using the next function
# Python program to demonstrate
# infinite iterators

import itertools

l = ['BCA', 'COM', 'BTEC']

# defining iterator
iterators = itertools.cycle(l)

# for in loop
for i in range(6):

	# Using next function
	print(next(iterators), end=" ")

#repeat(val, num):
# Python code to demonstrate the working of
# repeat()

# importing "itertools" for iterator operations
import itertools

# using repeat() to repeatedly print number
print("Printing the numbers repeatedly : ")
print(list(itertools.repeat(25, 9)))

"""# ***2. Combinatoric iterators***

The recursive generators that are used to simplify combinatorial constructs such as permutations, combinations, and Cartesian products are called combinatoric iterators.

Product():

Permutations()

Combinations():

Combinations_with_replacement():

# ***Product(): ***

This tool computes the cartesian product of input iterables. To compute the product of an iterable with itself, we use the optional repeat keyword argument to specify the number of repetitions. The output of this function is tuples in sorted order.
"""

# import the product function from itertools module
from itertools import product

print("The cartesian product using repeat:")
print(list(product([1, 4], repeat=2)))
print()

print("The cartesian product of the containers:")
print(list(product(['BCA', 'CSE', 'BTECH'], '2')))
print()

print("The cartesian product of the containers:")
print(list(product('AB', [3, 4])))

"""# ***Permutations():***
 Permutations() as the name speaks for itself is used to generate all possible permutations of an iterable. All elements are treated as unique based on their position and not their values. This function takes an iterable and group_size, if the value of group_size is not specified or is equal to None then the value of group_size becomes the length of the iterable.
"""

# import the product function from itertools module
from itertools import permutations

print("All the permutations of the given list is:")
print(list(permutations([1, 'MONITOR'], 2)))
print()

print("All the permutations of the given string is:")
print(list(permutations('AB')))
print()

print("All the permutations of the given container is:")
print(list(permutations(range(3), 2)))

"""# ***Combinations(): ***
This iterator prints all the possible combinations(without replacement) of the container passed in arguments in the specified group size in sorted order.
"""

# import combinations from itertools module

from itertools import combinations

print ("All the combination of list in sorted order(without replacement) is:")
print(list(combinations(['C', 2], 2)))
print()

print ("All the combination of string in sorted order(without replacement) is:")
print(list(combinations('CB', 2)))
print()

print ("All the combination of list in sorted order(without replacement) is:")
print(list(combinations(range(2), 1)))



"""# ***Combinations_with_replacement(): ***
This function returns a subsequence of length n from the elements of the iterable where n is the argument that the function takes determining the length of the subsequences generated by the function. Individual elements may repeat itself in combinations_with_replacement function
"""

# import combinations from itertools module

from itertools import combinations_with_replacement

print("All the combination of string in sorted order(with replacement) is:")
print(list(combinations_with_replacement("AB", 3)))
print()

print("All the combination of list in sorted order(with replacement) is:")
print(list(combinations_with_replacement([1, 3], 3)))
print()

print("All the combination of container in sorted order(with replacement) is:")
print(list(combinations_with_replacement(range(2), 1)))

"""# **Terminating iterators**
Terminating iterators are used to work on the short input sequences and produce the output based on the functionality of the method used.

Different types of terminating iterators are:

1.***accumulate(iter, func)***: This iterator takes two arguments, iterable target and the function which would be followed at each iteration of value in target. If no function is passed, addition takes place by default. If the input iterable is empty, the output iterable will also be empty
"""

# Python code to demonstrate the working of
# accumulate()


import itertools
import operator

# initializing list 1
li1 = [1,4,8,10]

# using accumulate()
# prints the successive summation of elements
print("The sum after each iteration is : ", end="")
print(list(itertools.accumulate(li1)))

# using accumulate()
# prints the successive multiplication of elements
print("The product after each iteration is : ", end="")
print(list(itertools.accumulate(li1, operator.mul)))

# using accumulate()
# prints the successive summation of elements
print("The sum after each iteration is : ", end="")
print(list(itertools.accumulate(li1)))

# using accumulate()
# prints the successive multiplication of elements
print("The product after each iteration is : ", end="")
print(list(itertools.accumulate(li1, operator.mul)))

"""## 2.**chain(iter1, iter2..):** This function is used to print all the values in iterable targets one after another mentioned in its arguments. *italicized text*"""

# Python code to demonstrate the working of
# and chain()


import itertools

# initializing list 1
li1 = [1, 5, 6, 7]

# initializing list 2
li2 = [1, 10, 2, 9]

# initializing list 3
li3 = [8, 12, 15, 4]

# using chain() to print all elements of lists
print("All values in mentioned chain are : ", end="")
print(list(itertools.chain(li1, li2, li3)))

"""# 3.***chain.from_iterable():*** This function is implemented similarly as a chain() but the argument here is a list of lists or any other iterable container."""

# Python code to demonstrate the working of
# chain.from_iterable()


import itertools


# initializing list 1
li1 = [1, 3, 5, 7]

# initializing list 2
li2 = [1, 7, 5, 9]

# initializing list 3
li3 = [8, 13, 5, 13]

# initializing list of list
li4 = [li1, li2, li3]

# using chain.from_iterable() to print all elements of lists
print ("All values in mentioned chain are : ", end ="")
print (list(itertools.chain.from_iterable(li4)))

"""# 4. ***compress(iter, selector):*** This iterator selectively picks the values to print from the passed container according to the boolean list value passed as other arguments. The arguments corresponding to boolean true are printed else all are skipped."""

# Python code to demonstrate the working of
# and compress()


import itertools


# using compress() selectively print data values
print("The compressed values in string are : ", end="")
print(list(itertools.compress('GEEKSFORGEEKS', [
	1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0])))

"""5.***dropwhile(func, seq):*** This iterator starts printing the characters only after the func. in argument returns false for the first time."""

# Python code to demonstrate the working of
# dropwhile()


import itertools


# initializing list
li = [8, 4, 2, 7, 8]

# using dropwhile() to start displaying after condition is false
print ("The values after condition returns false : ", end ="")
print (list(itertools.dropwhile(lambda x : x % 2 == 0, li)))

"""6. # ***dropwhile(func, seq):*** This iterator starts printing the characters only after the func. in argument returns false for the first time."""

# Python code to demonstrate the working of
# dropwhile()


import itertools


# initializing list
li = [2, 13, 5, 6, 8]

# using dropwhile() to start displaying after condition is false
print ("The values after condition returns false : ", end ="")
print (list(itertools.dropwhile(lambda x : x % 2 == 0, li)))

"""##7.  ***filterfalse(func, seq):*** As the name suggests, this iterator prints only values that return false for the passed function"""

# Python code to demonstrate the working of
# filterfalse()


import itertools

# initializing list
li = [2, 8, 10, 7, 8]

# using filterfalse() to print false values
print ("The values that return false to function are : ", end ="")
print (list(itertools.filterfalse(lambda x : x % 2 == 0, li)))

"""# 8.***islice(iterable, start, stop, step):***
This iterator selectively prints the values mentioned in its iterable container passed as argument. This iterator takes 4 arguments, iterable container, starting pos., ending position and step
"""

# Python code to demonstrate the working of
# islice()


import itertools

# initializing list
li = [2, 17, 5, 7, 8, 11, 20]

# using islice() to slice the list acc. to need
# starts printing from 2nd index till 6th skipping 2
print ("The sliced list values are : ", end ="")
print (list(itertools.islice(li, 1, 6, 2)))

"""# 9.***starmap(func., tuple list):***
This iterator takes a function and tuple list as argument and returns the value according to the function from each tuple of the list.
"""

# Python code to demonstrate the working of
# starmap()


import itertools


# initializing tuple list
li = [ (1, 10, 5), (8, 4, 1), (5, 4, 9), (11, 10, 1) ]

# using starmap() for selection value acc. to function
# selects min of all tuple values
print ("The values acc. to function are : ", end ="")
print (list(itertools.starmap(min, li)))

"""# 10. ***takewhile(func, iterable):*** This iterator is the opposite of dropwhile(), it prints the values till the function returns false for 1st time.
Example
"""

# Python code to demonstrate the working of
# takewhile()


import itertools

# initializing list
li = [2, 30, 6, 17, 8, 10, 20]

# using takewhile() to print values till condition is false.
print ("The list values till 1st false value are : ", end ="")
print (list(itertools.takewhile(lambda x : x % 2 == 0, li )))

"""##11 ***tee(iterator, count):- ***This iterator splits the container into a number of iterators mentioned in the argument."""

# Python code to demonstrate the working of
# tee()


import itertools

# initializing list
li = [6, 42, 61, 17, 8, 10, 20]

# storing list in iterator
iti = iter(li)

# using tee() to make a list of iterators
# makes list of 3 iterators having same values.
it = itertools.tee(iti, 3)

# printing the values of iterators
print("The iterators are : ")
for i in range(0, 3):
	print(list(it[i]))

"""#12 ***zip_longest( iterable1, iterable2, fillval):***
 This iterator prints the values of iterables alternatively in sequence. If one of the iterables is printed fully, the remaining values are filled by the values assigned to fillvalue
"""

# Python code to demonstrate the working of
# zip_longest()


import itertools

# using zip_longest() to combine two iterables.
print("The combined values of iterables is : ")
print(*(itertools.zip_longest('Peiec', 'rsdny', fillvalue='_')))

